services:
  dev-container-refmerge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-container-refmerge
    ports:
      - "127.0.0.1:3000:3000" # HTTP access: https://localhost:3000/
      - "127.0.0.1:3001:3001" # HTTPS access: https://localhost:3001/
      - "127.0.0.1:3002:6901" # HTTPS access (direct KasmVNC, no audio): https://localhost:3002/
    security_opt:
      - seccomp=unconfined # modern GUI desktop apps have issues with the latest Docker and syscall compatibility
    volumes:
      - dev_data_refmerge:/config # user directory
    environment:
      - PUID=1000 # user PUID
      - PGID=1000 # group PGID
      - TZ=Europe/Zurich # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - TITLE=Dev-RefMerge # the page title displayed on the web browser
      # - PASSWORD=nUuuDn*R6Q3$9^gzn0gR # HTTP Basic auth password, abc is default. If unset there will be no auth
    shm_size: "1gb" # we set this to 1 gig to prevent modern web browsers from crashing

volumes:
  dev_data_refmerge:
